# Este es el ejemplo de la clase del jueves

name: configurar-mysql

on:
  push:

jobs:
  db:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: admin
        ports:
          - 3306:3306

    steps:
      - name: Ejecutar
        run: ls


        


     
      
      
